- name: Check if nexus is installed
  shell: "docker ps -a|grep {{ NEXUS_CONTAINER_NAME }}|awk '{print $NF}'"
  register: nexus_container_name
  changed_when: False

- block:
  - import_tasks: nexus.yml
  - import_tasks: images.yml
  when: 'nexus_container_name.stdout == ""'
