apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-demo
  template:
    metadata:
      labels:
        app: project-demo
    spec:
      containers:
      - name: project-demo
        image: sherwinwangs/demo-project:1
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: project-demo
  name: project-demo
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: project-demo
  type: ClusterIP
