kube_proxy_image: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/google_containers/kube-proxy:v1.15.1"

# kube-proxy's iptables mode, ipvs or iptables(default value)


PROXY_MODE: '{%- if CLUSTER_NETWORK == "flannel" -%}
                "ipvs"
            {%- else -%}
                "iptables"
            {%- endif -%}'


# Setting APISERVERS ADDRESS
KUBE_APISERVER: "{%- if inventory_hostname in groups['kube_master'] -%} \
                     https://{{ inventory_hostname }}:6443 \
                 {%- else -%} \
                     {%- if groups['kube_master']|length > 1 -%} \
                         https://127.0.0.1:6443 \
                     {%- else -%} \
                         https://{{ groups['kube_master'][0] }}:6443 \
                     {%- endif -%} \
                 {%- endif -%}"
