coredns_image: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/google_containers/coredns:{{ IMAGE_COREDNS_VERSION }}"
nginx_ingress_controller_image: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/kubernetes-ingress-controller/nginx-ingress-controller:{{ IMAGE_NGINX_INGRESS_CONTROLLER_VERSION }}"
default_http_backend_image: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/google_containers/defaultbackend-amd64:{{ IMAGE_DEFAULTBACKEND_AMD64_VERSION }}"
CLUSTER_DNS_SVC_IP: "{{ SERVICE_CIDR | ipaddr('net') | ipaddr(2) | ipaddr('address') }}"
