# Docker log paramenters
LOG_DRIVER: "json-file"
LOG_LEVEL: "warn"
LOG_MAX_SIZE: "10m"
LOG_MAX_FILE: 3

# Docker datadir
STORAGE_DIR: "/data/docker"

# Enable Docker Restful API
ENABLE_REMOTE_API: false

# Enable docker registry mirror
ENABLE_REGISTRY_MIRROR: true

# Setting docker registry mirror
REGISTRY_MIRRORS: '["https://nvwtccbz.mirror.aliyuncs.com"]'

# Insecurity registrys
#INSECURE_REGISTRY: '["127.0.0.1/8"]'
