pause_image: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/google_containers/pause:{{ IMAGE_PAUSE_VERSION}}"

# Kubelet root dir
KUBELET_ROOT_DIR: "/var/lib/kubelet"

# Maximum number of pods that can be run on a node
MAX_PODS: 512


# Hard Eviction Conditions for Configuring Kubelet
HARD_EVICTION: "memory.available<500Mi,nodefs.available<10%"

# Setting the address of APISERVER
KUBE_APISERVER: "{%- if inventory_hostname in groups['kube_master'] -%} \
                     https://{{ inventory_hostname }}:6443 \
                 {%- else -%} \
                     {%- if groups['kube_master']|length > 1 -%} \
                         https://127.0.0.1:6443 \
                     {%- else -%} \
                         https://{{ groups['kube_master'][0] }}:6443 \
                     {%- endif -%} \
                 {%- endif -%}"