- import_tasks: centos.yml
  when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]'

- import_tasks: common.yml
  when: "inventory_hostname in groups['kube_master'] or inventory_hostname in groups['kube_node']"

- import_tasks: distribute.yml