- name: Check if kubelet is running
  uri:
    url: http://{{ inventory_hostname }}:10248/healthz
  register: kubernetes_kubelet
  until: kubernetes_kubelet.status == 200
  retries: 3
  delay: 1
  ignore_errors: true

- import_tasks: distribute.yml
  when: 'kubernetes_kubelet.status != 200'

- import_tasks: pre_pull_images.yml

- import_tasks: install_kubelet.yml
  when: 'kubernetes_kubelet.status != 200'
