- name: Create directory for kube-node
  file: name={{ item }} state=directory
  with_items:
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /etc/cni/net.d
    - /etc/kubernetes/yaml

- name: Download necessary binary files kubelet, kubectl, cni plugins
  copy: src={{ base_dir }}/bin/kubernetes/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
    - kubelet
    - kubectl
    - bridge
    - host-local
    - loopback
    - portmap
    - flannel

- name: Login private registry and force re-authorization
  docker_login:
    registry: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}"
    username: "admin"
    password: "{{ NEXUS_ADMIN_PASSWORD }}"
    reauthorize: yes
  ignore_errors: true

- name: Pull all image from configuration
  docker_image:
    name: "{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}/{{ item.target_group }}/{{ item.name }}:{{ item.tag }}"
    source: pull
  with_items: "{{ DOCKER_IMAGE_LIST }}"
  ignore_errors: true
