- name: Create secret for kubernetes access docker private registry
  shell: 'kubectl create secret docker-registry {{ PRIVATE_REGISTRY_SECRET_NAME }} \
         --docker-server="{{ groups.nexus[0] }}:{{ NEXUS_DOCKER_REGISTRY_PORT }}" \
         --docker-username=admin \
         --docker-password="{{ NEXUS_ADMIN_PASSWORD }}" \
         --docker-email=sherwinwangs@hotmail.com \
         -n kube-system >/dev/null 2>&1; echo $?'
  register: cmd_status
  until: cmd_status.stdout == "0"
  retries: 30
  delay: 2
  run_once: true
  ignore_errors: true
  tags: docker_registry
