- name: Check if kubernetes apiserver is running
  uri:
    url: http://127.0.0.1:8080/healthz
  register: kubernetes_apiserver
  until: kubernetes_apiserver.status == 200
  retries: 3
  delay: 1
  ignore_errors: true

- import_tasks: install_master.yml
  when: 'kubernetes_apiserver.status != 200'

- import_tasks: set_label.yml

- name: Check if secret is applied to kubernetes
  shell: "kubectl get secret -n kube-system|grep -w {{ PRIVATE_REGISTRY_SECRET_NAME }} >/dev/null 2>&1; echo $?"
  register: kubernetes_secret 
#- debug: msg="{{ kubernetes_secret.stdout }}"
- import_tasks: create_registry_secret.yml
  when: 'kubernetes_secret.stdout != "0"'
