- name: Setting master role name
  shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/master='' --overwrite"
  when: "inventory_hostname in groups['kube_master']"
  ignore_errors: true

# Add label for node node-role.kubernetes.io/master:NoSchedule
- name: Making master nodes SchedulingDisabled
  shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }}"
  when: "inventory_hostname in groups['kube_master']"
  ignore_errors: true