- name: Check if kubelet is running
  uri:
    url: http://{{ inventory_hostname }}:10248/healthz
  register: kubernetes_kubelet
  until: kubernetes_kubelet.status == 200
  retries: 3
  delay: 1
  ignore_errors: true

- name: Create directory for manifests
  file: name={{ item }} state=directory
  with_items:
    - "/etc/kubernetes/manifests"

- name: Gerenerate etcd yaml file
  template: src=etcd.yaml.j2 dest=/etc/kubernetes/manifests/etcd.yaml
  tags: upgrade_etcd

- name: Waiting for etcd start-up to complete
  shell: "docker ps|grep etcd|grep -v pause"
  register: etcd_status
  until: '"etcd" in etcd_status.stdout'
  retries: 30
  delay: 2
  tags: upgrade_etcd
  when: 'kubernetes_kubelet.status == 200'

