# CA Settings
CA_EXPIRY: "876000h"
CERT_EXPIRY: "438000h"

# apiserver default is first master node
KUBE_APISERVER: "https://{{ groups['kube_master'][0] }}:6443"

# kubeconfig parameters, different permission dependes on USER_NAME
# 'admin' user has fully access permission for kubernetes
# 'read' user has ony read permission for kubernetes
CLUSTER_NAME: "kubernetes"
USER_NAME: "admin"
CONTEXT_NAME: "context-{{ CLUSTER_NAME }}-{{ USER_NAME }}"
