- name: Create directory for kube-proxy
  file: name={{ item }} state=directory
  with_items:
    - /etc/kubernetes/yaml/kube_proxy

- name: Gerenerate kube-proxy yaml file
  template: src={{ item }}.j2 dest=/etc/kubernetes/yaml/kube_proxy/{{ item }}
  with_items:
    - kube-proxy-cm.yaml
    - kube-proxy-ds.yaml
  tags: restart_kube_proxy, upgrade_kube_proxy

- name: Apply kube-proxy to kubernetes
  shell: "{{ bin_dir }}/kubectl apply -f /etc/kubernetes/yaml/kube_proxy/{{ item }} >/dev/null 2>&1; echo $?"
  with_items:
    - kube-proxy-cm.yaml
    - kube-proxy-ds.yaml
  register: cmd_status
  until: cmd_status.stdout == "0"
  retries: 30
  delay: 2
  run_once: true
  ignore_errors: true

- name: Waiting for kube-proxy start-up to complete
  shell: "{{ bin_dir }}/kubectl get pod -n kube-system -o wide|grep 'kube-proxy'|grep ' {{ inventory_hostname }}   '|awk '{print $3}'"
  register: pod_status
  until: pod_status.stdout == "Running"
  retries: 30
  delay: 2
  ignore_errors: true
