- name: Check if kubernetes kube-proxy is running
  uri:
    url: http://127.0.0.1:10256/healthz
  register: kube_proxy
  until: kube_proxy.status == 200
  retries: 3
  delay: 1
  ignore_errors: true

- import_tasks: install_kube_proxy.yml
  when: 'kube_proxy.status != 200'
