- name: Create directory for certificate files
  file: name={{ item }} state=directory
  with_items:
    - "{{ base_dir }}/.cluster/ssl/etcd"

- name: Change binary directory permission
  file: path={{ base_dir }}/bin state=directory mode=0755 recurse=yes

- name: Read CA certificate state information According to the stat information of the registered variable p judged whether the CA certificate has been generated or not In order to ensure the idempotency of the whole installation If the CA certificate already exists The step is skipped
  stat: path="{{ base_dir }}/.cluster/ssl/ca.pem"
  register: p

- name: Prepare CA configuration file and certificate request file
  template: src={{ item }}.j2 dest={{ base_dir }}/.cluster/ssl/{{ item }}
  with_items:
    - "ca-config.json"
    - "ca-csr.json"
  when: p.stat.isreg is not defined

- name: Create CA certificate and private keys
  when: p.stat.isreg is not defined
  shell: "cd {{ base_dir }}/.cluster/ssl && \
	 {{ base_dir }}/bin/cfssl/cfssl gencert -initca ca-csr.json | {{ base_dir }}/bin/cfssl/cfssljson -bare ca"
