- name: Create directory for certificate files
  file: name={{ item }} state=directory
  with_items:
    - "{{ base_dir }}/.cluster/ssl/etcd"

- name: Change binary directory permission
  file: path={{ base_dir }}/bin state=directory mode=0755 recurse=yes

# 注册变量p，根据p的stat信息判断是否已经生成过ca证书，如果没有，下一步生成证书
# 如果已经有ca证书，为了保证整个安装的幂等性，跳过证书生成的步骤
- name: Read CA certificate state information
  stat: path="{{ base_dir }}/.cluster/ssl/ca.pem"
  register: p

- name: Prepare CA configuration file and certificate request file
  template: src={{ item }}.j2 dest={{ base_dir }}/.cluster/ssl/{{ item }}
  with_items:
    - "ca-config.json"
    - "ca-csr.json"
  when: p.stat.isreg is not defined

- name: Create CA certificate and private keys
  when: p.stat.isreg is not defined
  shell: "cd {{ base_dir }}/.cluster/ssl && \
	 {{ base_dir }}/bin/cfssl/cfssl gencert -initca ca-csr.json | {{ base_dir }}/bin/cfssl/cfssljson -bare ca"
