- name: Delete the original kubeconfig file ${HOME}/.kube/config
  file: path=/root/.kube/config state=absent
  ignore_errors: true

- name: repare the user {{ USER_NAME }} certificate request file for kubectl
  template: src={{ USER_NAME }}-csr.json.j2 dest={{ base_dir }}/.cluster/ssl/{{ USER_NAME }}-csr.json

- name: Create certificate and private keys for {{ USER_NAME }} user
  shell: "cd {{ base_dir }}/.cluster/ssl && {{ base_dir }}/bin/cfssl/cfssl gencert \
        -ca={{ base_dir }}/.cluster/ssl/ca.pem \
        -ca-key={{ base_dir }}/.cluster/ssl/ca-key.pem \
        -config={{ base_dir }}/.cluster/ssl/ca-config.json \
        -profile=kubernetes {{ base_dir }}/.cluster/ssl/{{ USER_NAME }}-csr.json | {{ base_dir }}/bin/cfssl/cfssljson -bare {{ USER_NAME }}"

- name: Setting cluster parameters
  shell: "{{ base_dir }}/bin/kubernetes/kubectl config set-cluster {{ CLUSTER_NAME }} \
        --certificate-authority={{ base_dir }}/.cluster/ssl/ca.pem \
        --embed-certs=true \
        --server={{ KUBE_APISERVER }}"

- name: Setting client authentication parameters
  shell: "{{ base_dir }}/bin/kubernetes/kubectl config set-credentials {{ USER_NAME }} \
        --client-certificate={{ base_dir }}/.cluster/ssl/{{ USER_NAME }}.pem \
        --embed-certs=true \
        --client-key={{ base_dir }}/.cluster/ssl/{{ USER_NAME }}-key.pem"

- name: Setting context references
  shell: "{{ base_dir }}/bin/kubernetes/kubectl config set-context {{ CONTEXT_NAME }} \
        --cluster={{ CLUSTER_NAME }} --user={{ USER_NAME }}"

- name: Select the default context
  shell: "{{ base_dir }}/bin/kubernetes/kubectl config use-context {{ CONTEXT_NAME }}"
