- name: repare certificate request file for kube-proxy
  template: src=kube-proxy-csr.json.j2 dest={{ base_dir }}/.cluster/ssl/kube-proxy-csr.json

- name: Create certificate and private keys for kube-proxy
  shell: "cd {{ base_dir }}/.cluster/ssl && {{ base_dir }}/bin/cfssl/cfssl gencert \
        -ca={{ base_dir }}/.cluster/ssl/ca.pem \
        -ca-key={{ base_dir }}/.cluster/ssl/ca-key.pem \
        -config={{ base_dir }}/.cluster/ssl/ca-config.json \
        -profile=kubernetes kube-proxy-csr.json | {{ base_dir }}/bin/cfssl/cfssljson -bare kube-proxy"
