- block:
    - name: Create directory for docker service
      file: name={{ item }} state=directory
      with_items:
      - "{{ bin_dir }}"
      - "/etc/docker"
    
    - name: Download docker binary from ansible controller(>= 18.09.x) TODO support more version
      copy: src={{ base_dir }}/bin/docker/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - docker-init
      - runc
      - docker
      - ctr
      - dockerd
      - docker-proxy
      tags: upgrade_docker, download_docker
    
    - name: Setting docker configuration file
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    
    - name: Flush iptables
      shell: "iptables -P INPUT ACCEPT \
            && iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle"
    
    - name: Setting systemd file for docker 
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker
    
    - name: Enable docker service start on boot
      shell: systemctl enable docker
      ignore_errors: true
    
    - name: Reload systemd and start docker
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    - name: Waiting for docker start-up to complete
      shell: "systemctl status docker.service|grep Active"
      register: docker_status
      until: '"running" in docker_status.stdout'
      retries: 8
      delay: 2
      tags: reload-docker, upgrade_docker, restart_docker
