- name: Check if docker is installed and running
  shell: "systemctl status docker.service|grep Active"
  register: docker_status
  ignore_errors: true

- import_tasks: install_docker.yml
  when: '"running" not in docker_status.stdout'

