# WARNNING: clean etcd data and configuration
- hosts:
  - etcd
  tasks:
  - name: remove etcd data and yaml config
    file: name={{ item }} state=absent
    with_items:
    - "/var/lib/etcd"
    - "/etc/kubernetes/manifests/etcd.yaml"
