- name: Generate coredns yaml file
  template: src={{ item }}.j2 dest=/etc/kubernetes/yaml/{{ item }}
  with_items:
    - coredns/coredns-rbac.yaml
    - coredns/coredns-cm.yaml
    - coredns/coredns-dp.yaml
    - coredns/coredns-svc.yaml

- name: Apply coredns to kubernetes only run once on master node
  shell: "{{ bin_dir }}/kubectl apply -f /etc/kubernetes/yaml/{{ item }}"
  with_items:
    - coredns/coredns-rbac.yaml
    - coredns/coredns-cm.yaml
    - coredns/coredns-dp.yaml
    - coredns/coredns-svc.yaml
  retries: 30
  delay: 2
  run_once: true
  ignore_errors: true

- name: Waiting for coredns start-up to complete
  shell: "{{ bin_dir }}/kubectl get pod -n kube-system -o wide|grep 'coredns'|awk '{print $3}'"
  register: pod_status
  until: '"Running" in pod_status.stdout'
  retries: 30
  delay: 2
  ignore_errors: true
